// AUTO-GENERATED by scripts/sync-privacy-policy.mjs — do not edit by hand.
// Source: https://docs.google.com/document/d/e/2PACX-1vSUAWMYdMYIzpFnxHc-k4OJo_DGWHf0MA1nk06g9XpSRsx3rUFHrvKaZz__gYSR2tlpW0jaGkLk_2XP/pub
// Regenerate: node scripts/sync-privacy-policy.mjs

export interface PrivacyPolicyBlock {
  type: 'h2' | 'h3' | 'p' | 'ul';
  text?: string;
  items?: string[];
}

export interface PrivacyPolicyMeta {
  label: string;
  value: string;
}

export const privacyPolicy: {
  title: string;
  meta: PrivacyPolicyMeta[];
  blocks: PrivacyPolicyBlock[];
} = {
  "title": "Privacy Policy for GroceryScan",
  "meta": [
    {
      "label": "Effective Date",
      "value": "July 4, 2026"
    },
    {
      "label": "Contact",
      "value": "masontuft@gmail.com"
    }
  ],
  "blocks": [
    {
      "type": "h2",
      "text": "Overview"
    },
    {
      "type": "p",
      "text": "GroceryScan (\"the App\") is a mobile application that scans grocery product barcodes, looks up store pricing and promotions, and estimates checkout totals including tax. This Privacy Policy explains what information the App collects, how it is used, and your choices regarding that information."
    },
    {
      "type": "p",
      "text": "The App does not require you to create an account, and it does not collect your name, email address, or any other directly identifying information."
    },
    {
      "type": "h2",
      "text": "Information We Collect"
    },
    {
      "type": "h3",
      "text": "1. Camera Data"
    },
    {
      "type": "p",
      "text": "The App uses your device's camera solely to scan product barcodes in real time. Camera images are processed on-device to detect a barcode; the App does not capture, store, or transmit photos or video."
    },
    {
      "type": "h3",
      "text": "2. Location Data"
    },
    {
      "type": "p",
      "text": "If you choose to enable location access, the App uses your device's GPS to determine your approximate location (city, state, and ZIP code) in order to find nearby stores and show location-relevant pricing. Only this coarse location information (not your precise GPS coordinates) is stored on your device or sent to our backend. You may instead enter your location manually, or decline location access entirely; the App will continue to function with manually entered or no location data."
    },
    {
      "type": "h3",
      "text": "3. Product and Basket Data"
    },
    {
      "type": "p",
      "text": "When you scan a barcode, the App sends the barcode number, an optional store identifier, and your coarse location (state/ZIP) to our backend service in order to look up product identity, current pricing, and applicable promotions. Items you add to your in-app shopping basket are stored locally on your device."
    },
    {
      "type": "h3",
      "text": "4. Automatically Collected Technical Data"
    },
    {
      "type": "p",
      "text": "Our backend infrastructure (Supabase) may log standard technical request data (such as timestamps and request metadata) for the purpose of operating and securing the service. We do not use this data for advertising or analytics, and the App does not integrate any third-party analytics or advertising SDKs."
    },
    {
      "type": "h2",
      "text": "How We Use Information"
    },
    {
      "type": "p",
      "text": "Information described above is used only to:"
    },
    {
      "type": "ul",
      "items": [
        "Identify scanned products and retrieve accurate, current pricing and promotions",
        "Estimate basket totals, including applicable sales tax",
        "Improve the reliability and performance of the scanning and pricing features"
      ]
    },
    {
      "type": "p",
      "text": "We do not sell your information, and we do not use it for advertising or marketing purposes."
    },
    {
      "type": "h2",
      "text": "Third-Party Services"
    },
    {
      "type": "p",
      "text": "To provide pricing and product data, the App's backend communicates with the following third-party services on your behalf:"
    },
    {
      "type": "ul",
      "items": [
        "Barcode identity lookup (upcitemdb.com)",
        "Store pricing providers: Kroger API, Instacart Connect API, SerpApi (for Walmart pricing), Walmart Marketplace API, and Target's Redsky API"
      ]
    },
    {
      "type": "p",
      "text": "These requests include only the barcode/product identifier, an optional store identifier, and coarse location data (state/ZIP) - never your name, precise location, or other directly identifying information. Each third-party provider's use of data it receives is governed by its own privacy policy."
    },
    {
      "type": "p",
      "text": "Our backend is hosted on Supabase (Postgres database and Edge Functions), which stores product, store, and pricing data used by the App."
    },
    {
      "type": "h2",
      "text": "Data Storage and Retention"
    },
    {
      "type": "ul",
      "items": [
        "Your shopping basket, cached product information, and location preference are stored locally on your device (using on-device storage) and persist until you clear the App's data or uninstall the App.",
        "Cached pricing data is refreshed automatically after a short period (a few hours) to keep prices current.",
        "We do not maintain user accounts or profiles, so there is no server-side personal data tied to an individual identity for us to retain beyond standard operational request logs."
      ]
    },
    {
      "type": "h2",
      "text": "Children's Privacy"
    },
    {
      "type": "p",
      "text": "The App is not directed to children under 13, and we do not knowingly collect personal information from children under 13."
    },
    {
      "type": "h2",
      "text": "Your Choices"
    },
    {
      "type": "ul",
      "items": [
        "You can deny or revoke camera and location permissions at any time through your device settings; core scanning and pricing features that depend on those permissions may be limited as a result.",
        "You can clear the App's locally stored data (basket, cached products, saved location) by clearing the App's storage/cache through your device settings or by uninstalling the App."
      ]
    },
    {
      "type": "h2",
      "text": "Changes to This Policy"
    },
    {
      "type": "p",
      "text": "We may update this Privacy Policy from time to time. Material changes will be reflected by an updated Effective Date at the top of this document."
    },
    {
      "type": "h2",
      "text": "Contact Us"
    },
    {
      "type": "p",
      "text": "If you have questions about this Privacy Policy, contact us at masontuft@gmail.com."
    }
  ]
};
